### ISSUE TITLE
No thumbnails generated

### ISSUE THREAD

**Issue by cn-patqian** [Piwigo/piwigo-videojs#173] opened 2021-02-23 09:26 UTC
Server win system
exiftool already installed
ffmpeg already installed
MediaInfo already installed

Synchronization results
1 video(s) selected
1 video(s) with metadata added
1 poster(s) created
0 thumbnail(s) created
0 warnings during synchronization
0 个错误在同步中发生

file: ./galleries/tv_tv/hh.mp4
metadata: 15 
format, formatprofile, codecid, type, filesize, duration, playtime_seconds, bitrate, width, height, 
display_aspect_ratio, frame_rate, sampling_rate, channel, date_creation
poster: ./galleries/tv_tv/pwg_representative/hh.jpg

In the directory
/galleries/tv_tv/pwg_representative/
not found
hh.jpg

**Comment by cn-patqian** [comment] 2021-02-23 18:03
Microsoft Windows [版本 10.0.14393]
(c) 2016 Microsoft Corporation。保留所有权利。

C:\>ffmpeg -version
ffmpeg version N-101191-g51a9f487ae Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 9.3-win32 (GCC) 20200320
configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libxml2 --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-opencl --enable-libvmaf --disable-vulkan --enable-libvorbis --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --disable-libglslang --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --disable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
libavutil      56. 65.100 / 56. 65.100
libavcodec     58.125.100 / 58.125.100
libavformat    58. 68.100 / 58. 68.100
libavdevice    58. 12.100 / 58. 12.100
libavfilter     7.107.100 /  7.107.100
libswscale      5.  8.100 /  5.  8.100
libswresample   3.  8.100 /  3.  8.100
libpostproc    55.  8.100 / 55.  8.100

C:\>ffprobe -version
ffprobe version N-101191-g51a9f487ae Copyright (c) 2007-2021 the FFmpeg developers
built with gcc 9.3-win32 (GCC) 20200320
configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libxml2 --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-opencl --enable-libvmaf --disable-vulkan --enable-libvorbis --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --disable-libglslang --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --disable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
libavutil      56. 65.100 / 56. 65.100
libavcodec     58.125.100 / 58.125.100
libavformat    58. 68.100 / 58. 68.100
libavdevice    58. 12.100 / 58. 12.100
libavfilter     7.107.100 /  7.107.100
libswscale      5.  8.100 /  5.  8.100
libswresample   3.  8.100 /  3.  8.100
libpostproc    55.  8.100 / 55.  8.100

C:\>MediaInfo --version
MediaInfo Command line,
MediaInfoLib - v20.09

C:\>avconv -version
avconv version 9.18, Copyright (c) 2000-2014 the Libav developers
  built on Mar  9 2015 03:17:22 with gcc 4.8.3 (Gentoo 4.8.3 p1.1, pie-0.5.9)
avconv 9.18
libavutil     52.  3. 0 / 52.  3. 0
libavcodec    54. 35. 0 / 54. 35. 0
libavformat   54. 20. 4 / 54. 20. 4
libavdevice   53.  2. 0 / 53.  2. 0
libavfilter    3.  3. 0 /  3.  3. 0
libavresample  1.  0. 1 /  1.  0. 1
libswscale     2.  1. 1 /  2.  1. 1

C:\>avprobe -version
avprobe version 9.18, Copyright (c) 2007-2014 the Libav developers
  built on Mar  9 2015 03:17:22 with gcc 4.8.3 (Gentoo 4.8.3 p1.1, pie-0.5.9)
avprobe 9.18
libavutil     52.  3. 0 / 52.  3. 0
libavcodec    54. 35. 0 / 54. 35. 0
libavformat   54. 20. 4 / 54. 20. 4
libavdevice   53.  2. 0 / 53.  2. 0
libavfilter    3.  3. 0 /  3.  3. 0
libavresample  1.  0. 1 /  1.  0. 1
libswscale     2.  1. 1 /  2.  1. 1

C:\>exiftool -ver
12.19

**Comment by EddyLB** [comment] 2024-11-11 17:47
Duplicate of #198.

**Closed by EddyLB** 2024-11-11 17:47 UTC
