### ISSUE TITLE
Does not recognize poster with .JPG extension 

### ISSUE THREAD

**Issue by truk39** [Piwigo/piwigo-videojs#159] opened 2019-11-27 00:14 UTC
I recently updated to current versions of Piwigo and videojs. Our pwg_representative files are filled with files that end in .JPG (all caps). They will no longer display the poster. I noticed an older folder that had a few posters displaying, noticed .jpg extensions were lower case. Is there a way to get it to recognize the .JPG all caps?

**Comment by EddyLB** [comment] 2024-11-18 17:00
Duplicate of https://github.com/Piwigo/Piwigo/issues/1171

**Closed by EddyLB** 2024-11-18 17:00 UTC
